server:
  port: 7071
  
spring:
  application:
    name: portal-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/portal-backend
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: TRACE